### ISSUE TITLE
Missing optional features

### ISSUE THREAD

**Issue by uday-rana** [vinhyan/barrierless#4]
The project has not implemented two of the required optional features:

1. allow the user to specify the model to use with the --model or -m flag

2. allow the user to specify an output filename using --output or -o:

```
# output to stdout
tool-name ./file.js

# output is written to file1-modified.js
tool-name file1.js -o file1-modified.js
```
3. allow the user to optionally specify their API key using --api-key or -a and the base URL using --base-url or -u:

4. allow the user to create an [.env file] in the current directory and have your tool automatically use it to set the API Key, Base URL, and any other config options you want.

5. pick a few of the [optional parameters you can set for chat completions](https://platform.openai.com/docs/api-reference/chat) (e.g., temperature) and allow the user to set them via command-line args or .env file

6. support streaming responses when writing to stdout.

7. come up with your own idea. If you have an idea not listed above, talk to your professor and see if it's OK to implement that (it probably is). #

**Comment by vinhyan** [comment]
added ```output``` and ```model``` option.
