### ISSUE TITLE
.gitignore doesn't ignore .env in root

### ISSUE THREAD

**Issue by uday-rana** [vinhyan/barrierless#5]
The project's `.gitignore` file does not ignore `.env` files located in the project's root directory.

**Comment by vinhyan** [comment]
The current `**/*.env` in `.gitignore` will ignore:
- A `.env` file in the root directory.
- Any `.env` files in subdirectories (e.g., src/.env, config/.env).

**Comment by vinhyan** [comment]
Closing this as this is not an issue.

**Comment by uday-rana** [comment]
oops

**Comment by uday-rana** [comment]
By the way if you want you could mark the issue as not planned instead of as completed

![image](https://github.com/user-attachments/assets/6be354ae-94c7-4603-aa17-c2a3d521d2e0)
