### ISSUE TITLE
Default language option behaves unexpectedly when input text is English

### ISSUE THREAD

**Issue by uday-rana** [vinhyan/barrierless#6]
The program's target language option is intended to be set to English by default according to the help message, but if the input text is in English it seems to infer the target language either randomly or from context based on the input text.

![image](https://github.com/user-attachments/assets/aa31c771-f3e9-4971-90c3-5b71ccc533c9)

![image](https://github.com/user-attachments/assets/f3835a52-2f8a-4721-9e34-6b8bc8c286d3)

**Comment by vinhyan** [comment]
Modified prompt to solve this issue. "English" (as default option) keyword is provided in the prompt
