### ISSUE TITLE
Could simplify code

### ISSUE THREAD

**Issue by uday-rana** [vinhyan/barrierless#8]
Some changes may be made to to the project make it easier to understand and work on:

- [x] Move Groq configuration above program initialization with commander
- [x] `main()` seems unnecessary since it contains two lines of code and there are more lines of code involved in creating and invoking the function than if it was omitted
- [ ] `prompt.js` seems unnecessary since it just contains a single function which places arguments into a template literal and returns them
- [x] Exporting `main()` and `getGroqChatCompletion()` seems unnecessary

**Comment by vinhyan** [comment]
removed main()

keeping prompt.js as a separate file as different prompts might be added for future development
